[Desktop Entry]
Type=X-GNOME-Metatheme
Name=reintse_milk_theme
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=reintse_milk_theme
GtkTheme=reintse_milk_theme
IconTheme=reintse_milk_theme
MetacityTheme=reintse_milk_theme
